---
title: "04-tidyverse-challenges"
author: "Donna T. Wrublewski"
date: "11/4/2021"
output: html_document
---

> ### Challenge 4.1 - Subsetting using select() and filter()
>
>  Using pipes, create a subset of the `surveys` data to include animals collected before
>  1995 and retain only the columns `year`, `sex`, and `weight`. Enter your solution as a code 
>  chunk below.

> ### Challenge 4.2 - Modifying a data frame with mutate()
>
>  Create a new data frame from the `surveys` data that meets the following
>  criteria: contains only the `species_id` column and a new column called
>  `hindfoot_half` containing values that are half the `hindfoot_length` values.
>  In this `hindfoot_half` column, there are no `NA`s and all values are less
>  than 30.
>
>  **Hint**: think about how the commands should be ordered to produce this 
> data frame!

> ### Challenge 4.3 - Working with count():
> 1. How many animals were caught in each `plot_type` surveyed?
> 2. Use `group_by()` and `summarize()` to find the mean, min, and max
> hindfoot length for each species (using `species_id`). Also add the 
> number of observations (hint: see `?n`).
> 3. What was the heaviest animal measured in each year? Return the columns `year`, `genus`, 
> `species_id`, and `weight`.

> ## Challenge 4.4 - Reshaping
> 1. Make a wide data frame with `year` as columns, `plot_id` as rows, and where the values are the 
> number of genera (plural of genus) per plot. You will need to summarize before reshaping, and use 
> the function `n_distinct` to get the number of unique genera within a chunk of data. It's a 
> powerful function! See `?n_distinct` for more.
>
> 2. Now take that data frame, and make it long again, so each row is a unique `plot_id` `year` 
> combination
>
> 3. The `surveys` data set is not truly wide or long because there are two columns of 
> measurement - `hindfoot_length` and `weight`.  This makes it difficult to do things like look at 
> the relationship between mean values of each measurement per year in different plot types.
> Let's walk through a common solution for this type of problem: 
>   a. First, use `gather` to create a truly long dataset where we have a key column 
>       called `measurement` and a `value` column that takes on the value of either 
>       `hindfoot_length` or `weight`. Hint: You'll need to specify which columns are being gathered.
>   b. With this new truly long data set, calculate the average of each `measurement` in each `year` 
>       for each different `plot_type`. Then `spread` them into a wide data set with a column for 
>       `hindfoot_length` > and `weight`. Hint: Remember, you only need to specify the key and 
>       value columns for `spread`.