---
title: "Conditional Subsetting"
author: "Kristin Briney; Donna Wrublewski"
output:
  html_document:
    toc: yes
    df_print: paged
  pdf_document: default

---
### Conditional subsetting

Another common way of subsetting is by using a logical vector. `TRUE` will
select the element with the same index, while `FALSE` will not:

`> weight_g <- c(21, 34, 39, 54, 55)`

`> weight_g[c(TRUE, FALSE, TRUE, TRUE, FALSE)]`

Typically, these logical vectors are not typed by hand, but are the output of
other functions or logical tests. For instance, if you wanted to select only the
values above 50, typing:

`> weight_g > 50`

will return logicals with TRUE for the indices that meet the given condition (i.e. greater 
than 50). So, we can use this to select only the values above 50:

`> weight_g[weight_g > 50]`

You can combine multiple tests using `&` (both conditions are true, AND) or `|`
(at least one of the conditions is true, OR):

`> weight_g[weight_g < 30 | weight_g > 50]`

`> weight_g[weight_g >= 30 & weight_g == 21]`

Here, `<` stands for "less than", `>` for "greater than", `>=` for "greater than
or equal to", and `==` for "equal to". The double equal sign `==` is a test for
numerical equality between the left and right hand sides, and should not be
confused with the single `=` sign, which performs variable assignment (similar
to `<-`).

A common task is to search for certain strings in a vector. One could use the
"or" operator `|` to test for equality to multiple values:

`> animals <- c("mouse", "rat", "dog", "cat")`

`> animals[animals == "cat" | animals == "rat"]`

The expression above returns both 'rat and 'cat'.

This can quickly become tedious. The function `%in%` allows you to test if any of the elements 
of a search vector are found:

`> animals %in% c("rat", "cat", "dog", "duck", "goat")`

`> animals[animals %in% c("rat", "cat", "dog", "duck", "goat")]`

> ### Challenge
>
> * Can you figure out why `"four" > "five"` returns `TRUE`?
